"""
Auto-generates wiki/Changelog.md and wiki/PR-Index.md from merged PR data.

Reads merged PR data from the GitHub CLI and produces two wiki pages:
  - Changelog: merged PRs grouped by date (most recent first)
  - PR Index: all merged PRs in a table with linked Discussion numbers

Usage:
    python backend/changelog.py generate         # writes wiki/Changelog.md and wiki/PR-Index.md
    python backend/changelog.py preview          # prints to stdout, no file write
    python backend/changelog.py                  # defaults to generate
"""

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# Allow running as a script from repo root: `python3 backend/changelog.py`
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

# Two names because this file spends both planes: merged PRs and their
# /pull/ URLs live with the code, the /discussions/ URL does not.
from backend._repo import CODE_REPO as _CODE_REPO_SLUG, REPO as _REPO_SLUG

_REPO_ROOT = Path(__file__).resolve().parent.parent
_CHANGELOG_OUTPUT = _REPO_ROOT / "wiki" / "Changelog.md"
_PR_INDEX_OUTPUT = _REPO_ROOT / "wiki" / "PR-Index.md"


# ---------------------------------------------------------------------------
# Data loader
# ---------------------------------------------------------------------------


def load_merged_prs(limit: int = 100) -> list[dict]:
    """Fetch merged PRs via gh CLI. Returns empty list on failure."""
    try:
        result = subprocess.run(
            [
                "gh", "pr", "list",
                "--repo", _CODE_REPO_SLUG,
                "--state", "merged",
                "--json", "number,title,body,mergedAt,author",
                "--limit", str(limit),
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode != 0:
            sys.stderr.write(f"gh pr list failed: {result.stderr.strip()}\n")
            return []
        return json.loads(result.stdout)
    except FileNotFoundError:
        sys.stderr.write("gh CLI not found — cannot fetch PR data.\n")
        return []
    except (json.JSONDecodeError, subprocess.TimeoutExpired, OSError) as exc:
        sys.stderr.write(f"Error fetching PRs: {exc}\n")
        return []


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _parse_merge_date(merged_at: str) -> str:
    """Return YYYY-MM-DD from an ISO-8601 timestamp string. Returns '' on failure."""
    if not merged_at:
        return ""
    try:
        dt = datetime.fromisoformat(merged_at.replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d")
    except ValueError:
        return ""


def _extract_discussion_number(body: str) -> str:
    """Return the first #NNN reference found in a PR body, or ''."""
    if not body:
        return ""
    match = re.search(r"#(\d+)", body)
    return match.group(1) if match else ""


def _sort_prs(prs: list[dict]) -> list[dict]:
    """Sort PRs by mergedAt descending (most recent first)."""
    def sort_key(pr: dict) -> str:
        return pr.get("mergedAt") or ""
    return sorted(prs, key=sort_key, reverse=True)


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------


def generate_changelog(prs: list[dict]) -> str:
    """Produce markdown changelog grouped by merge date."""
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = []

    lines.append(f"<!-- generated: {now_iso} -->")
    lines.append("# Changelog")
    lines.append("")
    lines.append(f"_Auto-generated {now_iso}_")
    lines.append("")

    sorted_prs = _sort_prs(prs)

    if not sorted_prs:
        lines.append("No merged PRs found.")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append(
            "_Auto-generated by [[changelog.py]]. Do not edit manually._"
        )
        lines.append("")
        return "\n".join(lines)

    # Group by date
    groups: dict[str, list[dict]] = {}
    for pr in sorted_prs:
        date = _parse_merge_date(pr.get("mergedAt", ""))
        if not date:
            date = "unknown"
        groups.setdefault(date, []).append(pr)

    # Emit sections in date-descending order
    for date in sorted(groups.keys(), reverse=True):
        lines.append(f"## {date}")
        lines.append("")
        for pr in groups[date]:
            num = pr.get("number", "?")
            title = pr.get("title") or "(no title)"
            author = (pr.get("author") or {}).get("login", "unknown")
            pr_url = (
                f"https://github.com/{_CODE_REPO_SLUG}/pull/{num}"
            )
            lines.append(f"- [#{num}]({pr_url}) {title} — @{author}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "_Auto-generated by [[changelog.py]]. Do not edit manually._"
    )
    lines.append("")

    return "\n".join(lines)


def generate_pr_index(prs: list[dict]) -> str:
    """Produce markdown PR index table with Discussion links."""
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = []

    lines.append(f"<!-- generated: {now_iso} -->")
    lines.append("# PR Index")
    lines.append("")
    lines.append(f"_Auto-generated {now_iso}_")
    lines.append("")

    sorted_prs = _sort_prs(prs)

    if not sorted_prs:
        lines.append("No merged PRs found.")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append(
            "_Auto-generated by [[changelog.py]]. Do not edit manually._"
        )
        lines.append("")
        return "\n".join(lines)

    lines.append("| PR | Title | Discussion | Merged |")
    lines.append("|----|-------|------------|--------|")

    for pr in sorted_prs:
        num = pr.get("number", "?")
        title = (pr.get("title", "(no title)") or "").replace("|", "\\|")
        body = pr.get("body", "") or ""
        merged_at = _parse_merge_date(pr.get("mergedAt", ""))
        pr_url = f"https://github.com/{_CODE_REPO_SLUG}/pull/{num}"

        disc_num = _extract_discussion_number(body)
        if disc_num:
            disc_url = (
                f"https://github.com/{_REPO_SLUG}/discussions/{disc_num}"
            )
            disc_cell = f"[#{disc_num}]({disc_url})"
        else:
            disc_cell = "—"

        lines.append(
            f"| [#{num}]({pr_url}) | {title} | {disc_cell} | {merged_at} |"
        )

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "_Auto-generated by [[changelog.py]]. Do not edit manually._"
    )
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="changelog",
        description="Generate wiki/Changelog.md and wiki/PR-Index.md from merged PR data.",
    )
    p.add_argument(
        "command",
        nargs="?",
        choices=["generate", "preview"],
        default="generate",
        help="generate (write files) or preview (stdout only). Default: generate.",
    )
    p.add_argument(
        "--limit",
        type=int,
        default=100,
        help="Maximum number of merged PRs to fetch (default: 100).",
    )
    p.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Directory to write Changelog.md and PR-Index.md into "
        f"(default: {_REPO_ROOT / 'wiki'}). Takes precedence over the default "
        "when set — derived artifacts should not land in the source tree.",
    )
    return p


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    prs = load_merged_prs(limit=args.limit)

    changelog_content = generate_changelog(prs)
    pr_index_content = generate_pr_index(prs)

    if args.command == "preview":
        print(changelog_content)
        print(pr_index_content)
        return 0

    # generate — write files to the output dir (default: wiki/)
    output_dir: Path = args.output_dir if args.output_dir is not None else (_REPO_ROOT / "wiki")
    output_dir.mkdir(parents=True, exist_ok=True)

    changelog_output = output_dir / "Changelog.md"
    pr_index_output = output_dir / "PR-Index.md"

    changelog_output.write_text(changelog_content, encoding="utf-8")
    print(f"Written: {changelog_output}")

    pr_index_output.write_text(pr_index_content, encoding="utf-8")
    print(f"Written: {pr_index_output}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
