#!/usr/bin/env bash
# tests/test_sandbox_payload_shape.sh
#
# D#2324 — the hook records the shape of the payload it is handed.
#
# This suite drives the real hooks/sandbox.py process with real payloads on
# stdin and reads the real files it writes. Asserting on
# record_payload_shape() alone would prove nothing about the branch it sits
# in: the probe is placed above every tier branch precisely so that it also
# fires on the foreign-defer and block paths, and only an end-to-end run
# exercises that placement.
#
# Three things are being measured, and they are different:
#   1. dedup is by KEY SET (acceptance 2) — the same keys with different
#      values write one row, a genuinely new key set writes a second;
#   2. exit status is 0 on every payload, well-formed or not (acceptance 3),
#      and no decision the hook already made changes;
#   3. no value other than session_id reaches the row. The row is written to
#      an append-only log with no cleanup path, so this is not a stylistic
#      preference.
#
# Every payload is generated by ONE python process up front, into
# $RUN_TMP/inputs/, so the suite stays well inside scripts/run-pr-tests.sh's
# 120s bound — it auto-routes tests/*.sh and kills what overruns. See the
# comment on m_huge.json for the one input whose size had to be chosen rather
# than maximised.
#
# Usage: bash tests/test_sandbox_payload_shape.sh
# Exit 0 = all tests passed; non-zero = at least one failure.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Same isolation as tests/test_sandbox_head_flip_warn.sh (D#2267):
# hooks/sandbox.py anchors its daily hook-events file to
# Path(__file__).parent.parent with no env override, so the suite must run
# against a materialised copy of hooks/ rooted elsewhere or it appends to the
# LIVE telemetry file — and, here, would also poison the live dedup markers so
# that a later real payload shape went unrecorded.
source "$REPO_ROOT/tests/lib/repo-root-fixture.sh"
FIXTURE_ROOT="$(repo_root_fixture_make "$REPO_ROOT")" || {
  echo "FAIL: could not create isolated repo-root fixture" >&2
  exit 1
}
HOOK="$FIXTURE_ROOT/hooks/sandbox.py"
MAIN_REPO="$FIXTURE_ROOT"
WORKTREE="$FIXTURE_ROOT/.claude/worktrees/testid123"
mkdir -p "$WORKTREE"

HOOK_EVENTS="$FIXTURE_ROOT/.autonomous-team/hook-events"
BLOCKS_FILE="$HOOK_EVENTS/blocks-$(date +%F).jsonl"
MARKER_DIR="$HOOK_EVENTS/payload-shapes"

RUN_TMP="$(mktemp -d /tmp/test_sandbox_payload_shape.XXXXXX)"
trap 'chmod -R u+rwX "$HOOK_EVENTS" 2>/dev/null; rm -rf "$RUN_TMP" "$FIXTURE_ROOT"' EXIT

# The audit copy lands in <state_dir>/audit.jsonl, which is append-only in
# production and has no cleanup path. Point the hook at a scratch state dir
# for the whole suite (CLAUDE.md, "AUTONOMOUS_TEAM_STATE_DIR in tests"), and
# never unset it while HOME is also unset — Path.home() falls back to the
# passwd entry, and that is the leak this suite would cause most easily.
export AUTONOMOUS_TEAM_STATE_DIR="$RUN_TMP/state"
mkdir -p "$AUTONOMOUS_TEAM_STATE_DIR"
AUDIT="$AUTONOMOUS_TEAM_STATE_DIR/audit.jsonl"

IN="$RUN_TMP/inputs"

# A distinctive marker planted in payload VALUES. Nothing that carries it may
# ever appear in a payload_shape row.
SECRET="sentinel-value-must-not-be-logged-9f3c"

PASS=0
FAIL=0
ok()  { echo "PASS: $1"; PASS=$((PASS + 1)); }
bad() { echo "FAIL: $1 — $2"; FAIL=$((FAIL + 1)); }

# ---------------------------------------------------------------------------
# Generate every payload in one interpreter start
# ---------------------------------------------------------------------------

python3 - "$IN" "$MAIN_REPO" "$SECRET" "$WORKTREE" <<'PYEOF' || { echo "FAIL: could not build payloads" >&2; exit 1; }
import json, os, sys

out, main_repo, secret, worktree = sys.argv[1:5]
os.makedirs(out, exist_ok=True)


def w(name, text):
    with open(os.path.join(out, name), "w") as fh:
        fh.write(text)


# Acceptance 2: three shapes — one, the same key set with different values,
# then a genuinely new key set.
w("p_base.json", json.dumps(
    {"tool_name": "Bash", "tool_input": {"command": "git status " + secret},
     "cwd": main_repo}))
w("p_same.json", json.dumps(
    {"cwd": main_repo + "/sub",
     "tool_input": {"command": "ls -la " + secret, "description": "d"},
     "tool_name": "Write"}))
w("p_extra.json", json.dumps(
    {"tool_name": "Bash", "tool_input": {"command": "echo " + secret},
     "cwd": main_repo, "session_id": "sess-abc-123"}))

# Malformed and hostile inputs.
w("m_empty.json", "")
w("m_notjson.json", "}{ not json")
w("m_list.json", "[1,2,3]")
w("m_string.json", '"just a string"')
w("m_number.json", "123")
w("m_null.json", "null")
w("m_emptyobj.json", "{}")
w("m_nul.json", json.dumps(
    {"tool_name": "Bash", "a\x00b": 1, "tool_input": {}, "cwd": "/x"}))
w("m_surrogate.json", json.dumps(
    {"tool_name": "Bash", "lone\ud800": 1, "tool_input": {}, "cwd": "/y"}))
_many = {"tool_name": "Bash", "tool_input": {}, "cwd": "/z"}
_many.update({f"k{i}": i for i in range(300)})
w("m_300keys.json", json.dumps(_many))
w("m_longkey.json", json.dumps(
    {"tool_name": "Bash", "tool_input": {}, "cwd": "/a", "x" * 3000: 1}))
# 100 KB, and deliberately not larger. hooks/sandbox_rules.classify_bash is
# superlinear in command length on this host — measured on code-plane/main
# and on this branch, identically, at 80ms / 1.0s / 127s for 10 KB / 100 KB /
# 1.2 MB. That cost is entirely pre-existing (the probe records key names, not
# values, and adds nothing measurable), but a 1.2 MB case here made this suite
# take 128s against scripts/run-pr-tests.sh's 120s bound, which would have
# read as a flaky new suite rather than as what it is. 100 KB already shows
# the probe does not touch values.
w("m_huge.json", json.dumps(
    {"tool_name": "Bash", "tool_input": {"command": "echo " + "A" * 100000},
     "cwd": "/b", "big": 1}))
_deep = 1
for _ in range(200):
    _deep = [_deep]
w("m_deep.json", json.dumps(
    {"tool_name": "Bash", "tool_input": {"command": "x"}, "cwd": "/c",
     "deep": _deep}))
w("m_sid_obj.json", json.dumps(
    {"tool_name": "Bash", "tool_input": {}, "cwd": "/d",
     "session_id": {"nested": "x" * 5000}, "marker": 1}))
w("m_sid_null.json", json.dumps(
    {"tool_name": "Bash", "tool_input": {}, "cwd": "/e",
     "session_id": None, "marker2": 1}))

# Adverse-condition payloads: each carries a unique extra key, so each is a
# genuinely unseen shape and the writer is actually reached rather than
# short-circuiting on the dedup marker.
for key in ("adv_absent", "adv_empty", "adv_sd500", "adv_ro", "adv_dir",
            "adv_full", "adv_home", "adv_events"):
    w(f"a_{key}.json", json.dumps(
        {"tool_name": "Bash", "tool_input": {"command": "git status"},
         "cwd": main_repo, key: 1}))

# Decisions that must be unchanged by the probe.
w("d_block.json", json.dumps(
    {"tool_name": "Bash", "tool_input": {"command": "git reset --hard HEAD~1"},
     "cwd": worktree}))
w("d_warn.json", json.dumps(
    {"tool_name": "Bash", "tool_input": {"command": "git reset --hard FETCH_HEAD"},
     "cwd": main_repo}))
PYEOF

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# run_hook <input-file-basename>; sets HOOK_EXIT and HOOK_STDERR
run_hook() {
  HOOK_EXIT=0
  python3 "$HOOK" <"$IN/$1" >/dev/null 2>"$RUN_TMP/stderr" || HOOK_EXIT=$?
  HOOK_STDERR="$(cat "$RUN_TMP/stderr" 2>/dev/null || true)"
}

# rows -> cumulative count of payload_shape rows in the daily hook-events file
rows() {
  local n
  n="$(grep -c '"kind": "payload_shape"' "$BLOCKS_FILE" 2>/dev/null || true)"
  printf '%s' "${n:-0}"
}

audit_rows() {
  local n
  n="$(grep -c '"kind": "payload_shape"' "$AUDIT" 2>/dev/null || true)"
  printf '%s' "${n:-0}"
}

# expect_rows <name> <expected-cumulative-count>
expect_rows() {
  local got
  got="$(rows)"
  if [[ "$got" -eq "$2" ]]; then ok "$1"; else bad "$1" "expected $2 payload_shape rows, got $got"; fi
}

# feed_expect_zero <name> <input-file> — acceptance 3, one payload at a time
feed_expect_zero() {
  run_hook "$2"
  if [[ "$HOOK_EXIT" -ne 0 ]]; then
    bad "$1" "expected exit 0 (the probe must never change a decision), got $HOOK_EXIT"
  else
    ok "$1"
  fi
}

# ---------------------------------------------------------------------------
# Acceptance 2 + 3 — dedup is by key set, and every payload exits 0
# ---------------------------------------------------------------------------

feed_expect_zero "first payload exits 0" p_base.json
expect_rows "a first-seen key set writes exactly one row" 1

feed_expect_zero "second payload (same key set) exits 0" p_same.json
expect_rows "the same key set with different values writes NO second row" 1

feed_expect_zero "third payload (extra key) exits 0" p_extra.json
expect_rows "a genuinely new key set writes a second row" 2

# Dedup has to be durable, not merely adjacent — re-feeding either shape after
# the other has been seen must still add nothing.
run_hook p_base.json
run_hook p_extra.json
expect_rows "re-feeding both known shapes writes nothing further" 2

# ---------------------------------------------------------------------------
# Row content — sorted(payload.keys()), session_id, and nothing else
# ---------------------------------------------------------------------------

python3 - "$BLOCKS_FILE" "$SECRET" <<'PYEOF' && ok "row content: sorted key names, session_id recorded, absence recorded as null" || bad "row content" "see message above"
import json, sys

rows = [json.loads(l) for l in open(sys.argv[1]) if '"payload_shape"' in l]
secret = sys.argv[2]
if len(rows) != 2:
    print(f"  expected 2 rows, got {len(rows)}"); sys.exit(1)

first, second = rows
if first["payload_keys"] != ["cwd", "tool_input", "tool_name"]:
    print(f"  first row payload_keys wrong: {first['payload_keys']}"); sys.exit(1)
if first["key_count"] != 3:
    print(f"  first row key_count wrong: {first['key_count']}"); sys.exit(1)
if first["session_id"] is not None:
    print(f"  a payload with no session_id must record null, got {first['session_id']!r}"); sys.exit(1)
if second["payload_keys"] != ["cwd", "session_id", "tool_input", "tool_name"]:
    print(f"  second row payload_keys wrong: {second['payload_keys']}"); sys.exit(1)
if second["session_id"] != "sess-abc-123":
    print(f"  second row session_id wrong: {second['session_id']!r}"); sys.exit(1)
if first["signature"] == second["signature"]:
    print("  two different key sets produced the same signature"); sys.exit(1)
for r in rows:
    if r.get("decision") != "observe":
        print(f"  decision must be 'observe', got {r.get('decision')!r}"); sys.exit(1)
    if secret in json.dumps(r):
        print("  a payload VALUE leaked into a payload_shape row"); sys.exit(1)
PYEOF

if [[ "$(audit_rows)" -eq 2 ]]; then
  ok "both rows are also written to <state_dir>/audit.jsonl"
else
  bad "both rows are also written to <state_dir>/audit.jsonl" "got $(audit_rows)"
fi

# ---------------------------------------------------------------------------
# Acceptance 3, the hard half — malformed and hostile inputs still exit 0
#
# hooks/sandbox.py runs on every tool call, so an exception here degrades the
# guardrail for everything. PR-b's security review set the bar at 33 malformed
# inputs with zero exceptions; these are the ones that reach THIS code path.
#
# Two separate assertions, because they are not the same claim.
#
# Exit 0 is acceptance 3 and applies to every input below without exception.
#
# The second is deliberately narrower than "the hook never raises". On a JSON
# top level that is not an object — [1,2,3], "a string", 123, null — the
# UNCHANGED hook already raises AttributeError at payload.get("tool_name"),
# catches it at module level, prints a traceback and fails open with exit 0.
# That is pre-existing behaviour on a path outside this Spec, measured against
# code-plane/main before this change, and nothing here fixes it. What this
# suite must show is that the probe adds no new raise of its own — so it
# asserts the traceback does not implicate payload_shape, rather than
# asserting there is no traceback at all.
# ---------------------------------------------------------------------------

malformed_case() {  # <name> <input-file>
  run_hook "$2"
  if [[ "$HOOK_EXIT" -ne 0 ]]; then
    bad "$1" "expected exit 0, got $HOOK_EXIT (stderr: ${HOOK_STDERR:0:200})"
  elif [[ "$HOOK_STDERR" == *"payload_shape"* ]]; then
    bad "$1" "the probe raised: ${HOOK_STDERR:0:400}"
  else
    ok "$1"
  fi
}

malformed_case "empty stdin"                        m_empty.json
malformed_case "not JSON at all"                    m_notjson.json
malformed_case "JSON list, not an object"           m_list.json
malformed_case "JSON string"                        m_string.json
malformed_case "JSON number"                        m_number.json
malformed_case "JSON null"                          m_null.json
malformed_case "empty JSON object"                  m_emptyobj.json
malformed_case "key with an embedded NUL"           m_nul.json
malformed_case "key with a lone surrogate"          m_surrogate.json
malformed_case "300 keys"                           m_300keys.json
malformed_case "a 3000-character key name"          m_longkey.json
malformed_case "100 KB command value"               m_huge.json
malformed_case "200-deep nesting"                   m_deep.json
malformed_case "session_id is an object"            m_sid_obj.json
malformed_case "session_id is null"                 m_sid_null.json

# Whatever those wrote, the log must still be line-delimited JSON, and no row
# may carry an unbounded key name or session_id.
python3 - "$BLOCKS_FILE" <<'PYEOF' && ok "every log line still parses as JSON, and rows stay bounded" || bad "log integrity after malformed inputs" "see message above"
import json, sys

bad = 0
for n, line in enumerate(open(sys.argv[1], encoding="utf-8", errors="surrogatepass"), 1):
    line = line.strip()
    if not line:
        continue
    try:
        row = json.loads(line)
    except Exception as exc:
        print(f"  line {n} is not valid JSON: {exc}"); bad += 1; continue
    if row.get("kind") != "payload_shape":
        continue
    if len(row["payload_keys"]) > 64:
        print(f"  line {n} has {len(row['payload_keys'])} key names (cap is 64)"); bad += 1
    if any(len(k) > 200 for k in row["payload_keys"]):
        print(f"  line {n} has an unbounded key name"); bad += 1
    sid = row.get("session_id")
    if sid is not None and len(sid) > 200:
        print(f"  line {n} has an unbounded session_id"); bad += 1
sys.exit(1 if bad else 0)
PYEOF

# The 300-key payload must report its true size even though the list is capped.
if grep -q '"key_count": 303' "$BLOCKS_FILE"; then
  ok "a truncated key list still reports the true key_count (303)"
else
  bad "a truncated key list still reports the true key_count" "no key_count 303 row found"
fi

# ---------------------------------------------------------------------------
# Adverse write conditions — exit 0 must hold on every one of them
# ---------------------------------------------------------------------------

adverse() {  # <name> <setup-fn> <teardown-fn> <input-file>
  local name="$1" setup="$2" teardown="$3" input="$4"
  "$setup"
  run_hook "$input"
  local exit_code="$HOOK_EXIT" err="$HOOK_STDERR"
  "$teardown"
  if [[ "$exit_code" -ne 0 ]]; then
    bad "$name" "expected exit 0, got $exit_code (stderr: ${err:0:200})"
  elif [[ "$err" == *"payload_shape"* ]]; then
    bad "$name" "the probe raised: ${err:0:400}"
  else
    ok "$name"
  fi
}

sd_absent()   { export AUTONOMOUS_TEAM_STATE_DIR="$RUN_TMP/does-not-exist"; }
sd_restore()  { export AUTONOMOUS_TEAM_STATE_DIR="$RUN_TMP/state"; }
sd_empty()    { export AUTONOMOUS_TEAM_STATE_DIR=""; }
sd_mode500()  { chmod 500 "$RUN_TMP/state"; }
sd_mode500_undo() { chmod 700 "$RUN_TMP/state"; }
audit_ro()    { touch "$AUDIT"; chmod 400 "$AUDIT"; }
audit_ro_undo() { chmod 600 "$AUDIT"; }
audit_dir()   { touch "$AUDIT"; mv "$AUDIT" "$RUN_TMP/audit.bak"; mkdir -p "$AUDIT"; }
audit_dir_undo() { rmdir "$AUDIT"; mv "$RUN_TMP/audit.bak" "$AUDIT"; }
audit_full()  { touch "$AUDIT"; mv "$AUDIT" "$RUN_TMP/audit.bak2"; ln -s /dev/full "$AUDIT"; }
audit_full_undo() { rm -f "$AUDIT"; mv "$RUN_TMP/audit.bak2" "$AUDIT"; }
home_unset()  { HOME_BAK="$HOME"; unset HOME; }
home_restore(){ export HOME="$HOME_BAK"; }
# Both directories, deliberately: the marker subdirectory already exists by
# now with its own mode, so denying writes only on its parent would still let
# the marker be created and the row be written — the case would pass while
# measuring nothing.
events_ro()   { chmod 500 "$MARKER_DIR" "$HOOK_EVENTS"; }
events_ro_undo() { chmod 700 "$HOOK_EVENTS" "$MARKER_DIR"; }

adverse "state dir absent"                   sd_absent  sd_restore      a_adv_absent.json
adverse "state dir set but empty"            sd_empty   sd_restore      a_adv_empty.json
adverse "state dir mode 500"                 sd_mode500 sd_mode500_undo a_adv_sd500.json
adverse "audit.jsonl mode 400"               audit_ro   audit_ro_undo   a_adv_ro.json
adverse "audit.jsonl replaced by a dir"      audit_dir  audit_dir_undo  a_adv_dir.json
adverse "audit.jsonl symlinked to /dev/full" audit_full audit_full_undo a_adv_full.json
adverse "HOME unset"                         home_unset home_restore    a_adv_home.json
adverse "hook-events dir mode 500"           events_ro  events_ro_undo  a_adv_events.json

if [[ "$(id -u)" -eq 0 ]]; then
  echo "NOTE: running as root — the mode-500/400 cases above cannot actually deny access."
fi

# The dir-mode-500 run could not create its marker, so that shape is still
# unseen; once the directory is writable again it records normally rather than
# being permanently lost.
run_hook a_adv_events.json
if grep -q '"adv_events"' "$BLOCKS_FILE"; then
  ok "a shape missed while the log dir was unwritable is recorded on the next call"
else
  bad "a shape missed while the log dir was unwritable is recorded on the next call" \
      "no row for that key set"
fi

# ---------------------------------------------------------------------------
# The probe changes no decision the hook already makes
# ---------------------------------------------------------------------------

run_hook d_block.json
if [[ "$HOOK_EXIT" -ne 2 ]]; then
  bad "a blocked worktree command is still blocked" "expected exit 2, got $HOOK_EXIT"
elif [[ "$HOOK_STDERR" != *"blocked by sandbox: git write-verb outside worktree"* ]]; then
  bad "a blocked worktree command is still blocked" "reason string changed: ${HOOK_STDERR:0:200}"
else
  ok "a blocked worktree command is still blocked, same reason string"
fi

run_hook d_warn.json
if [[ "$HOOK_EXIT" -eq 0 && "$HOOK_STDERR" == *"moves HEAD or the main ref"* ]]; then
  ok "the team_lead head_flip warning still fires and still exits 0"
else
  bad "the team_lead head_flip warning still fires" "exit=$HOOK_EXIT stderr=${HOOK_STDERR:0:200}"
fi

# ---------------------------------------------------------------------------
# Volume: the dedup markers are what keep this off the per-invocation path.
# ---------------------------------------------------------------------------

BEFORE="$(rows)"
i=0
while [[ "$i" -lt 5 ]]; do
  run_hook p_base.json
  i=$((i + 1))
done
if [[ "$(rows)" -eq "$BEFORE" ]]; then
  ok "5 further calls with a known shape write 0 additional rows"
else
  bad "5 further calls with a known shape write 0 additional rows" \
      "row count moved from $BEFORE to $(rows)"
fi

if [[ -d "$MARKER_DIR" ]]; then
  ok "dedup markers live under hook-events/payload-shapes/, beside the rows"
else
  bad "dedup markers live under hook-events/payload-shapes/" "$MARKER_DIR does not exist"
fi

# ---------------------------------------------------------------------------

echo
echo "test_sandbox_payload_shape.sh: $PASS passed, $FAIL failed"
[[ "$FAIL" -eq 0 ]]
