#!/usr/bin/env bash
# scripts/setup-deps.sh — install Python dependencies for the autonomous loop backend.
#
# Usage:
#   bash scripts/setup-deps.sh              # install from requirements.txt
#   bash scripts/setup-deps.sh --check      # verify all deps are importable (no install)
#   bash scripts/setup-deps.sh --venv       # create/activate .venv before installing
#
# This script is generated by loop-bootstrap during project setup.
# It wraps `pip install -r requirements.txt` with helpful diagnostics.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REQUIREMENTS="$REPO_ROOT/requirements.txt"

CHECK_ONLY=false
USE_VENV=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) CHECK_ONLY=true; shift ;;
    --venv)  USE_VENV=true; shift ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
done

if [[ ! -f "$REQUIREMENTS" ]]; then
  echo "ERROR: requirements.txt not found at $REQUIREMENTS" >&2
  echo "       Run: cp loop-bootstrap/templates/requirements.txt.template requirements.txt" >&2
  echo "       Then edit it to match your project's needs." >&2
  exit 1
fi

if [[ "$CHECK_ONLY" == "true" ]]; then
  echo "Checking Python deps from $REQUIREMENTS..."
  MISSING=()
  while IFS= read -r line; do
    # Skip comments and empty lines
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${line// }" ]] && continue
    # Extract package name (before version specifier)
    pkg="${line%%[>=<!]*}"
    pkg="${pkg%%[[:space:]]*}"
    pkg="${pkg%%#*}"
    [[ -z "$pkg" ]] && continue
    # Map pip package names to Python import names where they differ.
    # pip name → import name (only entries that actually differ need listing here).
    declare -A IMPORT_NAMES=(
      ["pyyaml"]="yaml"
      ["PyJWT"]="jwt"
    )
    # Normalise: pip uses underscores, imports may use hyphens; then apply alias table.
    import_name="${pkg//-/_}"
    import_name="${IMPORT_NAMES[$pkg]:-${IMPORT_NAMES[${pkg,,}]:-$import_name}}"
    if python3 -c "import $import_name" 2>/dev/null; then
      echo "  OK: $pkg"
    else
      echo "  MISSING: $pkg"
      MISSING+=("$pkg")
    fi
  done < "$REQUIREMENTS"
  if [[ ${#MISSING[@]} -gt 0 ]]; then
    echo ""
    echo "Missing packages: ${MISSING[*]}"
    echo "Run: bash scripts/setup-deps.sh"
    exit 1
  else
    echo "All dependencies present."
    exit 0
  fi
fi

if [[ "$USE_VENV" == "true" ]]; then
  VENV_DIR="$REPO_ROOT/.venv"
  if [[ ! -d "$VENV_DIR" ]]; then
    echo "Creating virtualenv at $VENV_DIR..."
    python3 -m venv "$VENV_DIR"
  fi
  # Activate in current shell — only works if caller does `source` or `.`
  # We export PATH so pip/python resolve to the venv.
  export PATH="$VENV_DIR/bin:$PATH"
  echo "Using venv: $VENV_DIR"
fi

echo "Installing Python deps from $REQUIREMENTS..."
pip install -r "$REQUIREMENTS"

echo ""
echo "Done. Run 'bash scripts/setup-deps.sh --check' to verify all imports resolve."
