"""backend/corpus_drift/report.py — renders Markdown + writes JSON snapshot.

Consumers: scripts/corpus-drift-audit.py (CLI entrypoint).
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence

from backend.corpus_drift.types import ClaimResult

_STATUS_EMOJI = {
    "healthy": "✅",
    "watch": "⚠️",
    "drift": "🔴",
    "n/a": "—",
}


def _status_icon(status: str) -> str:
    return _STATUS_EMOJI.get(status, "?")


def render_markdown(
    results: Sequence[ClaimResult],
    window_days: int,
    generated_at: datetime,
    sample_cap: int,
    report_path: Path,
) -> str:
    """Render a Markdown report and write it to *report_path*.

    Returns the rendered Markdown string.
    """
    now_iso = generated_at.strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = [
        "# Corpus Drift Report",
        "",
        "**What this is:** A weekly audit comparing stated agent behavior (`.claude/agents/*.md`,",
        "`CLAUDE.md`) against observed behavior in recent agent runs.",
        "",
        f"**Generated:** {now_iso}  ",
        f"**Window:** last {window_days} days  ",
        f"**Sample cap:** {sample_cap} runs per role  ",
        "",
        "**Score meanings:**",
        "- `healthy` — ≥ 75% of runs honor the claim",
        "- `watch` — 50–74% (degrading, not yet critical)",
        "- `drift` — < 50% (methodology layer has decayed)",
        "- `n/a` — fewer than 5 samples; not enough data to score",
        "",
        "**Adding a new claim:** Create `backend/corpus_drift/claims/<slug>.py`,",
        "implement `evaluate()`, and register the claim in `scripts/corpus-drift-audit.py`.",
        "",
        "**JSON archive:** `$STATE_DIR/corpus-drift/<YYYY-MM-DD>.json`",
        "",
        "---",
        "",
        "## Results",
        "",
        "| Claim ID | Role | N | Score | Status | Evidence |",
        "|---|---|---|---|---|---|",
    ]

    for r in results:
        icon = _status_icon(r.status)
        score_str = r.score_display()
        evidence = r.evidence.replace("|", "\\|")
        lines.append(
            f"| `{r.claim_id}` | `{r.role_scope}` | {r.sample_size} "
            f"| {score_str} | {icon} {r.status} | {evidence} |"
        )

    lines += ["", "---", "", "## Findings", ""]

    drift_results = [r for r in results if r.status in ("drift", "watch")]
    healthy_results = [r for r in results if r.status == "healthy"]
    na_results = [r for r in results if r.status == "n/a"]

    if not drift_results and healthy_results:
        lines.append(
            f"No drift detected. All {len(healthy_results)} scored claim(s) are healthy."
        )
        if na_results:
            lines.append(
                f"\n{len(na_results)} claim(s) returned `n/a` (insufficient sample data):"
            )
            for r in na_results:
                lines.append(f"- `{r.claim_id}`: {r.evidence}")
    elif not drift_results and not healthy_results:
        lines.append("All claims returned `n/a` — no sufficient data in this window.")
        lines.append("Run again after more agent activity has been recorded.")
    else:
        for r in drift_results:
            lines += [
                f"### {_status_icon(r.status)} `{r.claim_id}` — {r.status.upper()}",
                "",
                f"- **Role scope:** `{r.role_scope}`",
                f"- **Score:** {r.score_display()} (N={r.sample_size})",
                f"- **Evidence:** {r.evidence}",
            ]
            if r.notes:
                lines.append(f"- **Notes:** {r.notes}")
            lines.append("")

        if healthy_results:
            lines += [
                "### Healthy claims",
                "",
                *[f"- `{r.claim_id}` — {r.score_display()} (N={r.sample_size})" for r in healthy_results],
                "",
            ]

    lines += [
        "---",
        "",
        "_Auto-generated by `scripts/corpus-drift-audit.py`. Do not edit manually._",
        "",
    ]

    content = "\n".join(lines)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(content, encoding="utf-8")
    return content


def write_json_snapshot(
    results: Sequence[ClaimResult],
    window_days: int,
    generated_at: datetime,
    snapshot_path: Path,
) -> None:
    """Write a dated JSON snapshot of all claim results to *snapshot_path*."""
    snapshot_path.parent.mkdir(parents=True, exist_ok=True)

    payload = {
        "generated_at": generated_at.isoformat(),
        "window_days": window_days,
        "claims": [
            {
                "claim_id": r.claim_id,
                "role_scope": r.role_scope,
                "sample_size": r.sample_size,
                "score": r.score,
                "score_type": r.score_type,
                "status": r.status,
                "evidence": r.evidence,
                "notes": r.notes,
            }
            for r in results
        ],
        "summary": {
            "healthy": sum(1 for r in results if r.status == "healthy"),
            "watch": sum(1 for r in results if r.status == "watch"),
            "drift": sum(1 for r in results if r.status == "drift"),
            "na": sum(1 for r in results if r.status == "n/a"),
        },
    }

    snapshot_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
