#!/usr/bin/env bash
# Guards against hardcoded absolute checkout paths — an absolute path under a
# user's home directory that names a specific project checkout — surviving in
# the tracked tree. Filed for D#1767, after a stale one in run-loop-iteration.sh
# was found to be a live, silently-broken defect (a cron entry that fails and
# cron just logs a missing file and moves on).
#
# Deliberately does not spell out the two example paths from that bug inline —
# they'd match this file's own PATTERN below and self-flag on every run.
#
# What a green result establishes (D#2018): it certifies the absence of
# literal checkout-path substrings of the derived shapes below — the exact
# resolved checkout path, and a home/Users/root path ending in this repo's
# basename — from the tracked tree; it does NOT certify the absence of
# hardcoded paths in general (string-built, split-across-lines, or
# otherwise adversarially disguised paths are out of scope — see
# CLAUDE.md's "hooks/ is a Guardrail, Not a Security Boundary").
#
# Lives under scripts/, not tests/ (D#1877 review round 2): scripts/lib/
# preflight-common.sh calls this as a wired-in gate, and scripts/ is what
# ships in the open-source export (open-source/MANIFEST.md's PATHS_START) —
# tests/ does not. A guard whose caller ships but the guard itself doesn't
# is a permanently red preflight for every export consumer and coldstart.
# tests/test_no_hardcoded_checkout_paths_guard.sh, this file's own hermetic
# test suite, stays under tests/ on purpose — it's a test, not something
# preflight needs to run in an exported tree.
#
# Scope: `git ls-files` output only — never the working tree — so
# .claude/worktrees/ and other untracked cruft are structurally excluded.
# archive/** is excluded by construction: archived material is a historical
# record and must never be edited to satisfy this guard. wiki/Changelog.md
# and wiki/Project-Status.md are excluded by construction too, for the same
# reason a different way: both are machine-generated by scripts/sync-wiki.sh
# from PR/Discussion titles, so a hit there is a title, not source — and
# escaping path-shaped strings in the generator would mangle legitimate
# changelog output to satisfy a check those files were never the subject of.
# tests/test_no_hardcoded_checkout_paths_guard.sh is excluded the same way:
# its synthetic mutation fixtures deliberately contain the pattern as test
# data, and being untracked-until-committed is exactly the blind spot this
# guard exists to close — a scan that only sees committed content missed
# its own harness during review (D#1877 review round 2). All three
# exclusions are scoped to one exact path each, never a directory prefix
# or a glob, and tests/test_no_hardcoded_checkout_paths_guard.sh asserts
# that scope can't silently widen.
#
# Allowlist keys on <path>:<content-hash>, not <path>:<line> and not
# whole-file (D#1877, both rounds). Whole-file keying let 25 files go from
# enforced to fully unprotected when the pattern widened under D#1857 and
# no one noticed — path:line closed that, but line numbers shift on every
# unrelated edit above them: one import added to the top of an 11-entry
# test file turned into 22 spurious failures (11 unlisted-match + 11
# stale-entry) from a single edit that never touched a flagged line. A
# hash of the matched line's own (whitespace-trimmed) content survives
# reflow and reordering and only goes stale when the content itself
# changes — which is exactly when it should. Every other match must be
# listed in scripts/fixtures/allowed_checkout_path_literals.txt with a
# written reason. An unlisted match fails the build — and so does a stale
# entry (no current line in that file hashes to this value anymore) or a
# dangling one (path no longer in `git ls-files`, e.g. a file the
# allowlist still names after it was deleted). Silently exempting a match
# that no longer exists is the same failure mode as exempting the whole
# file: an allowlist that can't go wrong out loud.
#
# The seen-map / stale-detection shape below is the same one
# open-source/checks/identifier-gate.sh:202-208 uses (init every allowlist
# key to unseen, mark seen on a hit, fail anything still unseen after the
# scan) — copied here as ~6 lines rather than sourced, because that script
# is bound to IDENTIFIER-RULES.txt's block-marker format, keys on
# path:line rather than content, and validates an export target-dir, not
# this repo's own `git ls-files`.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1

# Every scan and every stale/dangling check below depends on `git ls-files`
# actually listing something. If this isn't a git repo at all, `git
# ls-files` exits non-zero and prints nothing — silently indistinguishable
# from "a git repo with zero tracked files", which would make every
# allowlist entry look dangling (169 misleading failures instead of one
# clear one, D#1877 review round 3). Checked once, up front, as its own
# named failure.
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "FAIL: not a git repository — this guard requires \`git ls-files\` to determine the tracked file set, and cannot run outside one" >&2
  exit 1
fi

ALLOWLIST="scripts/fixtures/allowed_checkout_path_literals.txt"

if [ ! -f "$ALLOWLIST" ]; then
  echo "FAIL: allowlist file $ALLOWLIST not found" >&2
  exit 1
fi

# PATTERN derivation (D#2018). Was a literal '/home/(agent|jp)' — this
# operator's two usernames, hardcoded — so a checkout under any third
# username was structurally invisible to the guard that is supposed to be
# proving no checkout path is hardcoded. No username is spelled out below;
# PATTERN is computed at runtime from wherever the checkout actually is.
#
# PATTERN_ROOT is deliberately a SEPARATE variable from REPO_ROOT above.
# REPO_ROOT is the *scan* root — where `git ls-files` runs, always this
# checkout (inside a worktree, the worktree itself). PATTERN_ROOT is the
# *pattern* root — the checkout a hardcoded literal would actually name.
# Inside a worktree those differ: _resolve_main_repo_root() (the D#1998
# canonical resolver) walks past the worktree to the main checkout it was
# branched from, which is what deserves to be in the pattern. Conflating
# the two would derive the pattern's basename from a worktree directory
# name instead of the repo's real one.
#
# _resolve_main_repo_root() honours AUTONOMOUS_TEAM_REPO_ROOT as its first
# branch (see repo-root-resolve.sh) — that's the override this file's own
# test fixtures use to pin what "the checkout" is, rather than inventing a
# second variable for the same purpose.
source "$(dirname "${BASH_SOURCE[0]}")/lib/repo-root-resolve.sh"
PATTERN_ROOT="$(_resolve_main_repo_root)"
PATTERN_BASENAME="$(basename "$PATTERN_ROOT")"

# ERE-escape a literal string for safe embedding in $PATTERN below — a
# checkout path can contain regex metacharacters (a directory named
# "foo.bar", for instance) that must be matched literally, not as regex
# syntax.
_escape_ere() {
  printf '%s' "$1" | sed -e 's/[][\.^$*+?(){}|]/\\&/g'
}

_PATTERN_ROOT_ESC="$(_escape_ere "$PATTERN_ROOT")"
_PATTERN_BASENAME_ESC="$(_escape_ere "$PATTERN_BASENAME")"

# Two components, unioned:
#   1. The exact resolved checkout path — catches it on any host, any
#      layout, including a checkout not under a home directory at all.
#   2. A home-directory-shaped path keyed on THIS repo's basename, under
#      ANY username: /home/<user>/<basename>, /Users/<user>/<basename>
#      (macOS), /root/<basename>. This is what generalises coverage past
#      "agent" and "jp" to an arbitrary third username, a CI runner's
#      home, or a Mac — the whole point of D#2018 — while still refusing
#      to fire on every unrelated "/home/*" mention in the tree (a plain
#      "/home/[^/]+/" catch-all would be far too broad to be useful).
# Guarded against an empty basename (e.g. a checkout at the filesystem
# root) making the second component "/home/[^/]+/" — that would match
# almost anything.
PATTERN="$_PATTERN_ROOT_ESC"
if [ -n "$_PATTERN_BASENAME_ESC" ]; then
  PATTERN="${PATTERN}|/home/[^/]+/${_PATTERN_BASENAME_ESC}|/Users/[^/]+/${_PATTERN_BASENAME_ESC}|/root/${_PATTERN_BASENAME_ESC}"
fi

FAIL=0

# trim() — strip leading/trailing whitespace before hashing, so reindenting
# an allowlisted line doesn't manufacture a spurious stale entry. Same
# idiom as identifier-gate.sh's trim().
trim() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "$s"
}

hash_line() {
  trim "$1" | sha256sum | cut -c1-12
}

# Allowlisted path:hash keys — format is <path>:<hash>:<reason>, comments
# and blank lines skipped. A malformed entry (missing a field, or a hash
# that isn't 12 hex chars) is itself a hard failure rather than a silent
# skip.
# Banned reason families (D#1997). The allowlist was drained from 169 entries
# to zero, and the drain found that two whole families of reason were not
# "unfinished work described honestly" but wrong statements nobody re-checked:
#
#   "not a live hardcode" sat on the constant that made the worktree
#   contamination classifier dead on its host for months, and on a
#   SubagentStop hook resolving to a directory that did not exist.
#
#   Deferrals outlived what they deferred to. Three entries pointed at draft
#   PR #1813 for a fix that "lives there, not here"; that PR was closed months
#   before anyone read the entries again. Others deferred to a Discussion's
#   "scope" that had long since closed.
#
# Both families share a property that makes them worth rejecting mechanically
# rather than in review: they describe a state of the world *outside* this
# file, so they rot silently, and the allowlist has no way to notice. A reason
# that has to stay true about another PR's status is not a reason, it is a
# bet. Reject on sight instead.
#
# Deliberately NOT a substring blocklist on the paths themselves — this matches
# on the reason field only, so a file whose *content* legitimately discusses
# these phrases is unaffected.
_BANNED_REASON_RES=(
  'not a live hardcode'
  'flag for follow-up'
  'owned by'
  'out of .* scope'
  'parked'
  'lives there, not here'
)

# Human-readable name per pattern, so the failure says which family was hit
# rather than echoing a regex at the reader.
_BANNED_REASON_NAMES=(
  'claims the literal is not live — the drain found live ones wearing this exact reason'
  'defers to a follow-up that nothing tracks'
  'defers ownership to another Discussion or agent'
  'defers to another ticket'"'"'s scope'
  'defers to parked work'
  'defers the fix to another PR'
)

declare -A ALLOWLIST_SEEN
ALLOWLIST_KEYS=()
while IFS= read -r entry; do
  path="${entry%%:*}"
  rest="${entry#*:}"
  hash="${rest%%:*}"
  reason="${rest#*:}"
  if [[ -z "$path" || ! "$hash" =~ ^[0-9a-f]{12}$ || -z "$reason" || "$reason" == "$rest" ]]; then
    echo "FAIL: malformed allowlist entry (need path:hash:reason, hash = 12 hex chars): $entry" >&2
    FAIL=1
    continue
  fi

  # Reason vetting. Case-insensitive: the ban is on the claim, not on how the
  # writer capitalised it.
  _reason_lc="${reason,,}"
  for _i in "${!_BANNED_REASON_RES[@]}"; do
    if [[ "$_reason_lc" =~ ${_BANNED_REASON_RES[$_i]} ]]; then
      echo "FAIL: banned reason in allowlist entry '$path:$hash' — ${_BANNED_REASON_NAMES[$_i]}" >&2
      echo "      reason given: $reason" >&2
      echo "      An allowlist entry needs a *mechanical* impossibility (the file is byte-compared" >&2
      echo "      against an external artifact this repo does not control, or similar). Being a" >&2
      echo "      fixture, being prose, and being historical are not mechanical impossibilities —" >&2
      echo "      see the header of $ALLOWLIST for what each of those resolved to instead." >&2
      FAIL=1
      break
    fi
  done
  key="$path:$hash"
  ALLOWLIST_KEYS+=("$key")
  ALLOWLIST_SEEN["$key"]=0
done < <(grep -vE '^\s*(#|$)' "$ALLOWLIST")

# Tracked files containing the pattern, excluding archive/** by
# construction (a whole subtree, by design) and three exact files by
# construction (never via an allowlist entry, so none of these three can
# go stale): the two generated wiki files, and this guard's own hermetic
# test harness (its synthetic mutation fixtures deliberately contain the
# pattern as test data). Each -vxF is a literal full-line match against
# `git ls-files` output — not a prefix, not a glob — so the exclusion is
# structurally incapable of widening past the one path it names;
# tests/test_no_hardcoded_checkout_paths_guard.sh asserts this directly
# with a near-miss filename that must NOT be excluded.
mapfile -t MATCH_FILES < <(
  git ls-files \
    | grep -v '^archive/' \
    | grep -vxF 'wiki/Changelog.md' \
    | grep -vxF 'wiki/Project-Status.md' \
    | grep -vxF 'tests/test_no_hardcoded_checkout_paths_guard.sh' \
    | xargs -r -d '\n' grep -lE "$PATTERN" -- 2>/dev/null
)

TOTAL_MATCHES=0
for f in "${MATCH_FILES[@]}"; do
  [ -z "$f" ] && continue
  # NOTE: deliberately NOT `IFS=: read -r lineno line` — bash's read strips
  # a trailing IFS delimiter from the final field, so a matched line that
  # itself ends in a literal ':' (e.g. `for path in [...]:`) would silently
  # lose that last character before hashing, and the recomputed hash would
  # never match the allowlist. Prefix-stripping on the first colon only
  # (via parameter expansion, same idiom the allowlist parser above uses)
  # keeps every trailing colon in the content intact.
  while IFS= read -r rawline; do
    [ -z "$rawline" ] && continue
    lineno="${rawline%%:*}"
    line="${rawline#*:}"
    TOTAL_MATCHES=$((TOTAL_MATCHES + 1))
    hash="$(hash_line "$line")"
    key="$f:$hash"
    if [[ -n "${ALLOWLIST_SEEN[$key]+x}" ]]; then
      ALLOWLIST_SEEN["$key"]=1
      continue
    fi
    echo "FAIL: $f:$lineno contains a hardcoded checkout path and is not in $ALLOWLIST" >&2
    FAIL=1
  done < <(grep -nE "$PATTERN" -- "$f")
done

# Dangling entries (path no longer tracked at all) and stale entries (path
# tracked, but no current matching line in that file hashes to this value
# anymore) both hard-fail, naming the key — the class of defect PR #1894
# introduced by deleting 417 files without touching the 24 entries that
# named them.
declare -A TRACKED
while IFS= read -r t; do
  TRACKED["$t"]=1
done < <(git ls-files)

for key in "${ALLOWLIST_KEYS[@]}"; do
  path="${key%:*}"
  if [[ -z "${TRACKED[$path]+x}" ]]; then
    echo "FAIL: dangling allowlist entry '$key' — $path is not in git ls-files" >&2
    FAIL=1
    continue
  fi
  if [[ "${ALLOWLIST_SEEN[$key]}" -eq 0 ]]; then
    echo "FAIL: stale allowlist entry '$key' — no current line in $path hashes to this value" >&2
    FAIL=1
  fi
done

if [ "$FAIL" -ne 0 ]; then
  exit 1
fi

echo "OK: no unlisted hardcoded checkout paths ($TOTAL_MATCHES matches, all allowlisted with reasons)"
exit 0
